Repository DragonQuestAPI/medias, pull requests merged in 2024-02, with the labels that each got.

#7 Added families icons
  DQM3/families_icons/beast.jpg
  DQM3/families_icons/demon.jpg
  DQM3/families_icons/dragon.jpg
  DQM3/families_icons/material.jpg
  DQM3/families_icons/nature.jpg
  DQM3/families_icons/slime.jpg
  DQM3/families_icons/special.jpg
  DQM3/families_icons/undead.jpg
Labels: enhancement

#8 Added eggs and skills icons
  DQM3/eggs_icons/egg_white.png
  DQM3/eggs_icons/golden_egg.png
  DQM3/eggs_icons/rainbow_egg.png
  DQM3/eggs_icons/silver_egg.png
  DQM3/skills_icons/attacking.png
  DQM3/skills_icons/healing.png
  DQM3/skills_icons/support.png
Labels: enhancement

#9 Renamed white_egg
  DQM3/eggs_icons/white_egg.png
Labels: bug

#11 Updated icons
  DQM3/items_icons/battle.png
  DQM3/items_icons/battle.webp
  DQM3/items_icons/bonus_ball.png
  DQM3/items_icons/bonus_ball.webp
  DQM3/items_icons/scroll.png
  DQM3/items_icons/scroll.webp
  DQM3/items_icons/seasoning.png
  DQM3/items_icons/seasoning.webp
Labels: enhancement

#12 Updated icons
  DQM3/informations_icons/family_tree.webp
  DQM3/informations_icons/identity.webp
  DQM3/informations_icons/resistances.webp
  DQM3/informations_icons/talents.webp
  DQM3/informations_icons/traits.webp
  DQM3/stats_icons/defense.webp
Labels: enhancement

#13 Changed resistances icons from PNG to WEBP
  DQM3/resistances_icons/antimagic.png
  DQM3/resistances_icons/antimagic.webp
  DQM3/resistances_icons/bedazzlement.png
  DQM3/resistances_icons/bedazzlement.webp
  DQM3/resistances_icons/confusion.png
  DQM3/resistances_icons/confusion.webp
  DQM3/resistances_icons/dark.png
  DQM3/resistances_icons/dark.webp
  DQM3/resistances_icons/debilitation.png
  DQM3/resistances_icons/debilitation.webp
  DQM3/resistances_icons/earth.png
  DQM3/resistances_icons/earth.webp
  DQM3/resistances_icons/electricity.png
  DQM3/resistances_icons/electricity.webp
  DQM3/resistances_icons/explosions.png
  DQM3/resistances_icons/explosions.webp
  DQM3/resistances_icons/fire.png
  DQM3/resistances_icons/fire.webp
  DQM3/resistances_icons/ice.png
  DQM3/resistances_icons/ice.webp
  DQM3/resistances_icons/instant_death.png
  DQM3/resistances_icons/instant_death.webp
  DQM3/resistances_icons/light.png
  DQM3/resistances_icons/light.webp
  DQM3/resistances_icons/mp_absorption.png
  DQM3/resistances_icons/mp_absorption.webp
  DQM3/resistances_icons/paralysis.png
  DQM3/resistances_icons/paralysis.webp
  DQM3/resistances_icons/poison.png
  DQM3/resistances_icons/poison.webp
  DQM3/resistances_icons/sleep.png
  DQM3/resistances_icons/sleep.webp
  DQM3/resistances_icons/stun.png
  DQM3/resistances_icons/stun.webp
  DQM3/resistances_icons/water.png
  DQM3/resistances_icons/water.webp
  DQM3/resistances_icons/wind.png
  DQM3/resistances_icons/wind.webp
Labels: bug, enhancement
